pipeline{
    agent any
        environment {
        DOCKER_IMAGE = 'kevalp566/ci-cd-project1'
    }

    stages{

        stage("Clone Repo")
        {
            steps{
                git branch: 'main', url: 'https://github.com/kevalp566/jenkins-ci-demo.git'
            }
        }

        stage('Build & Test') {
            dir('CI_CD_Project1') {
                steps {
                    sh 'npm install'
                    sh 'npm test'
                }
            }
        }

stage('Docker Build & Push') {
            dir('CI_CD_Project1') {
                steps {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker build -t $DOCKER_IMAGE:latest .
                            docker push $DOCKER_IMAGE:latest
                        '''
                    }
                }
            }
        }
    }
}
